packages:
  - example
engineStrict: true
managePackageManagerVersions: true
overrides:
  vite: 'npm:rolldown-vite@latest'
catalogs:
  build:
    typescript: ^5.9.2
    vite: 'npm:rolldown-vite@latest'
onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
useNodeVersion: 22.15.0
