packages:
  - example
engineStrict: true
managePackageManagerVersions: true
catalogs:
  build:
    vite: 'npm:rolldown-vite@latest'
onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
useNodeVersion: 22.15.0
