name: Deploy Example Page

on:
  push:
    branches:
      - main

jobs:
  build-page:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
        working-directory: example
      - uses: actions/upload-pages-artifact@v3
        with:
          path: example/build

  deploy-to-github-pages:
    needs: build-page
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
